/* resolves all dom element references once at startup so other modules don't call getElementById directly */

const $ = id => document.getElementById(id);

export const dom = {
    historyBtn: $('history-btn'),
    historyDropdown: $('history-dropdown'),
    historyClose: $('history-close'),
    historyList: $('history-list'),
    newChatBtn: $('new-chat-btn'),
    importBtn: $('import-btn'),
    importInput: $('import-input'),
    exportBtn: $('export-btn'),
    settingsBtn: $('settings-btn'),
    modelStatus: $('model-status'),
    statusText: $('model-status').querySelector('.status-text'),
    welcomeScreen: $('welcome-screen'),
    welcomeTitle: $('welcome-title'),
    welcomeSubtitle: $('welcome-subtitle'),
    messagesContainer: $('messages-container'),
    messages: $('messages'),
    attachmentsPreview: $('attachments-preview'),
    storageDisclaimer: $('storage-disclaimer'),
    messageInput: $('message-input'),
    attachBtn: $('attach-btn'),
    fileInput: $('file-input'),
    sendBtn: $('send-btn'),
    inputBox: $('input-box'),
    dinoRunner: $('dino-runner'),
    settingsPanel: $('settings-panel'),
    settingsClose: $('settings-close'),
    sAiName: $('s-ai-name'),
    sUserName: $('s-user-name'),
    sSystemPrompt: $('s-system-prompt'),
    sWelcomeMsg: $('s-welcome-msg'),
    settingsSave: $('settings-save'),
    settingsReset: $('settings-reset'),
    storageInfo: $('storage-info'),
    clearStorageBtn: $('clear-storage-btn'),
    setupModal: $('setup-modal'),
    setupTitle: $('setup-title'),
    setupMessage: $('setup-message'),
    setupProgress: $('setup-progress'),
    progressFill: $('progress-fill'),
    progressText: $('progress-text'),
    setupLang: $('setup-lang'),
    langGrid: $('lang-grid'),
    setupDownloadBtn: $('setup-download-btn'),
    setupError: $('setup-error'),
    setupErrorMsg: $('setup-error-msg'),
};
